/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MyDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Attribute_CommaKeyword_4_q;
	protected AbstractElementAlias match_Collection___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q;
	protected AbstractElementAlias match_Collection___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q;
	protected AbstractElementAlias match_Collection___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q;
	protected AbstractElementAlias match_Disclosure___RefersToEnforcementKeyword_15_0_CommaKeyword_15_2__q;
	protected AbstractElementAlias match_Disclosure___RefersToPrivateDataKeyword_13_0_CommaKeyword_13_2__q;
	protected AbstractElementAlias match_Disclosure___RefersToRecipientKeyword_10_0_CommaKeyword_10_2__q;
	protected AbstractElementAlias match_Disclosure___RefersToRecipientSourceKeyword_11_0_CommaKeyword_11_2__q;
	protected AbstractElementAlias match_Disclosure___RefersToRecipientTargetKeyword_12_0_CommaKeyword_12_2__q;
	protected AbstractElementAlias match_Disclosure___RefersToServiceKeyword_14_0_CommaKeyword_14_2__q;
	protected AbstractElementAlias match_Informative___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q;
	protected AbstractElementAlias match_Informative___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q;
	protected AbstractElementAlias match_Informative___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q;
	protected AbstractElementAlias match_Partof_HyphenMinusKeyword_1_q;
	protected AbstractElementAlias match_Recipient___Recipient_PartKeyword_9_0_CommaKeyword_9_2__q;
	protected AbstractElementAlias match_RefPrivateData_HyphenMinusKeyword_1_q;
	protected AbstractElementAlias match_ReferToRecipientSource_HyphenMinusKeyword_1_q;
	protected AbstractElementAlias match_ReferToRecipientTarget_HyphenMinusKeyword_1_q;
	protected AbstractElementAlias match_ReferToRecipient_HyphenMinusKeyword_1_q;
	protected AbstractElementAlias match_ReferToService_HyphenMinusKeyword_1_q;
	protected AbstractElementAlias match_RefertoEnforcement_HyphenMinusKeyword_1_q;
	protected AbstractElementAlias match_Retention___RefersToEnforcementKeyword_15_0_CommaKeyword_15_2__q;
	protected AbstractElementAlias match_Retention___RefersToPrivateDataKeyword_13_0_CommaKeyword_13_2__q;
	protected AbstractElementAlias match_Retention___RefersToServiceKeyword_14_0_CommaKeyword_14_2__q;
	protected AbstractElementAlias match_ServicePartof_HyphenMinusKeyword_1_q;
	protected AbstractElementAlias match_Service_Service_PartKeyword_8_0_q;
	protected AbstractElementAlias match_Service___RefersToPrivateDataKeyword_7_0_CommaKeyword_7_2__q;
	protected AbstractElementAlias match_Usage___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q;
	protected AbstractElementAlias match_Usage___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q;
	protected AbstractElementAlias match_Usage___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MyDslGrammarAccess) access;
		match_Attribute_CommaKeyword_4_q = new TokenAlias(false, true, grammarAccess.getAttributeAccess().getCommaKeyword_4());
		match_Collection___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getCollectionAccess().getRefersToEnforcementKeyword_12_0()), new TokenAlias(false, false, grammarAccess.getCollectionAccess().getCommaKeyword_12_2()));
		match_Collection___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getCollectionAccess().getRefersToPrivateDataKeyword_10_0()), new TokenAlias(false, false, grammarAccess.getCollectionAccess().getCommaKeyword_10_2()));
		match_Collection___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getCollectionAccess().getRefersToServiceKeyword_11_0()), new TokenAlias(false, false, grammarAccess.getCollectionAccess().getCommaKeyword_11_2()));
		match_Disclosure___RefersToEnforcementKeyword_15_0_CommaKeyword_15_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDisclosureAccess().getRefersToEnforcementKeyword_15_0()), new TokenAlias(false, false, grammarAccess.getDisclosureAccess().getCommaKeyword_15_2()));
		match_Disclosure___RefersToPrivateDataKeyword_13_0_CommaKeyword_13_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDisclosureAccess().getRefersToPrivateDataKeyword_13_0()), new TokenAlias(false, false, grammarAccess.getDisclosureAccess().getCommaKeyword_13_2()));
		match_Disclosure___RefersToRecipientKeyword_10_0_CommaKeyword_10_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDisclosureAccess().getRefersToRecipientKeyword_10_0()), new TokenAlias(false, false, grammarAccess.getDisclosureAccess().getCommaKeyword_10_2()));
		match_Disclosure___RefersToRecipientSourceKeyword_11_0_CommaKeyword_11_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDisclosureAccess().getRefersToRecipientSourceKeyword_11_0()), new TokenAlias(false, false, grammarAccess.getDisclosureAccess().getCommaKeyword_11_2()));
		match_Disclosure___RefersToRecipientTargetKeyword_12_0_CommaKeyword_12_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDisclosureAccess().getRefersToRecipientTargetKeyword_12_0()), new TokenAlias(false, false, grammarAccess.getDisclosureAccess().getCommaKeyword_12_2()));
		match_Disclosure___RefersToServiceKeyword_14_0_CommaKeyword_14_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDisclosureAccess().getRefersToServiceKeyword_14_0()), new TokenAlias(false, false, grammarAccess.getDisclosureAccess().getCommaKeyword_14_2()));
		match_Informative___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getInformativeAccess().getRefersToEnforcementKeyword_12_0()), new TokenAlias(false, false, grammarAccess.getInformativeAccess().getCommaKeyword_12_2()));
		match_Informative___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getInformativeAccess().getRefersToPrivateDataKeyword_10_0()), new TokenAlias(false, false, grammarAccess.getInformativeAccess().getCommaKeyword_10_2()));
		match_Informative___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getInformativeAccess().getRefersToServiceKeyword_11_0()), new TokenAlias(false, false, grammarAccess.getInformativeAccess().getCommaKeyword_11_2()));
		match_Partof_HyphenMinusKeyword_1_q = new TokenAlias(false, true, grammarAccess.getPartofAccess().getHyphenMinusKeyword_1());
		match_Recipient___Recipient_PartKeyword_9_0_CommaKeyword_9_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRecipientAccess().getRecipient_PartKeyword_9_0()), new TokenAlias(false, false, grammarAccess.getRecipientAccess().getCommaKeyword_9_2()));
		match_RefPrivateData_HyphenMinusKeyword_1_q = new TokenAlias(false, true, grammarAccess.getRefPrivateDataAccess().getHyphenMinusKeyword_1());
		match_ReferToRecipientSource_HyphenMinusKeyword_1_q = new TokenAlias(false, true, grammarAccess.getReferToRecipientSourceAccess().getHyphenMinusKeyword_1());
		match_ReferToRecipientTarget_HyphenMinusKeyword_1_q = new TokenAlias(false, true, grammarAccess.getReferToRecipientTargetAccess().getHyphenMinusKeyword_1());
		match_ReferToRecipient_HyphenMinusKeyword_1_q = new TokenAlias(false, true, grammarAccess.getReferToRecipientAccess().getHyphenMinusKeyword_1());
		match_ReferToService_HyphenMinusKeyword_1_q = new TokenAlias(false, true, grammarAccess.getReferToServiceAccess().getHyphenMinusKeyword_1());
		match_RefertoEnforcement_HyphenMinusKeyword_1_q = new TokenAlias(false, true, grammarAccess.getRefertoEnforcementAccess().getHyphenMinusKeyword_1());
		match_Retention___RefersToEnforcementKeyword_15_0_CommaKeyword_15_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRetentionAccess().getRefersToEnforcementKeyword_15_0()), new TokenAlias(false, false, grammarAccess.getRetentionAccess().getCommaKeyword_15_2()));
		match_Retention___RefersToPrivateDataKeyword_13_0_CommaKeyword_13_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRetentionAccess().getRefersToPrivateDataKeyword_13_0()), new TokenAlias(false, false, grammarAccess.getRetentionAccess().getCommaKeyword_13_2()));
		match_Retention___RefersToServiceKeyword_14_0_CommaKeyword_14_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRetentionAccess().getRefersToServiceKeyword_14_0()), new TokenAlias(false, false, grammarAccess.getRetentionAccess().getCommaKeyword_14_2()));
		match_ServicePartof_HyphenMinusKeyword_1_q = new TokenAlias(false, true, grammarAccess.getServicePartofAccess().getHyphenMinusKeyword_1());
		match_Service_Service_PartKeyword_8_0_q = new TokenAlias(false, true, grammarAccess.getServiceAccess().getService_PartKeyword_8_0());
		match_Service___RefersToPrivateDataKeyword_7_0_CommaKeyword_7_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getServiceAccess().getRefersToPrivateDataKeyword_7_0()), new TokenAlias(false, false, grammarAccess.getServiceAccess().getCommaKeyword_7_2()));
		match_Usage___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getUsageAccess().getRefersToEnforcementKeyword_12_0()), new TokenAlias(false, false, grammarAccess.getUsageAccess().getCommaKeyword_12_2()));
		match_Usage___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getUsageAccess().getRefersToPrivateDataKeyword_10_0()), new TokenAlias(false, false, grammarAccess.getUsageAccess().getCommaKeyword_10_2()));
		match_Usage___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getUsageAccess().getRefersToServiceKeyword_11_0()), new TokenAlias(false, false, grammarAccess.getUsageAccess().getCommaKeyword_11_2()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_Attribute_CommaKeyword_4_q.equals(syntax))
				emit_Attribute_CommaKeyword_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Collection___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q.equals(syntax))
				emit_Collection___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Collection___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q.equals(syntax))
				emit_Collection___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Collection___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q.equals(syntax))
				emit_Collection___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Disclosure___RefersToEnforcementKeyword_15_0_CommaKeyword_15_2__q.equals(syntax))
				emit_Disclosure___RefersToEnforcementKeyword_15_0_CommaKeyword_15_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Disclosure___RefersToPrivateDataKeyword_13_0_CommaKeyword_13_2__q.equals(syntax))
				emit_Disclosure___RefersToPrivateDataKeyword_13_0_CommaKeyword_13_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Disclosure___RefersToRecipientKeyword_10_0_CommaKeyword_10_2__q.equals(syntax))
				emit_Disclosure___RefersToRecipientKeyword_10_0_CommaKeyword_10_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Disclosure___RefersToRecipientSourceKeyword_11_0_CommaKeyword_11_2__q.equals(syntax))
				emit_Disclosure___RefersToRecipientSourceKeyword_11_0_CommaKeyword_11_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Disclosure___RefersToRecipientTargetKeyword_12_0_CommaKeyword_12_2__q.equals(syntax))
				emit_Disclosure___RefersToRecipientTargetKeyword_12_0_CommaKeyword_12_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Disclosure___RefersToServiceKeyword_14_0_CommaKeyword_14_2__q.equals(syntax))
				emit_Disclosure___RefersToServiceKeyword_14_0_CommaKeyword_14_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Informative___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q.equals(syntax))
				emit_Informative___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Informative___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q.equals(syntax))
				emit_Informative___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Informative___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q.equals(syntax))
				emit_Informative___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Partof_HyphenMinusKeyword_1_q.equals(syntax))
				emit_Partof_HyphenMinusKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Recipient___Recipient_PartKeyword_9_0_CommaKeyword_9_2__q.equals(syntax))
				emit_Recipient___Recipient_PartKeyword_9_0_CommaKeyword_9_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_RefPrivateData_HyphenMinusKeyword_1_q.equals(syntax))
				emit_RefPrivateData_HyphenMinusKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ReferToRecipientSource_HyphenMinusKeyword_1_q.equals(syntax))
				emit_ReferToRecipientSource_HyphenMinusKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ReferToRecipientTarget_HyphenMinusKeyword_1_q.equals(syntax))
				emit_ReferToRecipientTarget_HyphenMinusKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ReferToRecipient_HyphenMinusKeyword_1_q.equals(syntax))
				emit_ReferToRecipient_HyphenMinusKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ReferToService_HyphenMinusKeyword_1_q.equals(syntax))
				emit_ReferToService_HyphenMinusKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_RefertoEnforcement_HyphenMinusKeyword_1_q.equals(syntax))
				emit_RefertoEnforcement_HyphenMinusKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Retention___RefersToEnforcementKeyword_15_0_CommaKeyword_15_2__q.equals(syntax))
				emit_Retention___RefersToEnforcementKeyword_15_0_CommaKeyword_15_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Retention___RefersToPrivateDataKeyword_13_0_CommaKeyword_13_2__q.equals(syntax))
				emit_Retention___RefersToPrivateDataKeyword_13_0_CommaKeyword_13_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Retention___RefersToServiceKeyword_14_0_CommaKeyword_14_2__q.equals(syntax))
				emit_Retention___RefersToServiceKeyword_14_0_CommaKeyword_14_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_ServicePartof_HyphenMinusKeyword_1_q.equals(syntax))
				emit_ServicePartof_HyphenMinusKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Service_Service_PartKeyword_8_0_q.equals(syntax))
				emit_Service_Service_PartKeyword_8_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Service___RefersToPrivateDataKeyword_7_0_CommaKeyword_7_2__q.equals(syntax))
				emit_Service___RefersToPrivateDataKeyword_7_0_CommaKeyword_7_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Usage___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q.equals(syntax))
				emit_Usage___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Usage___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q.equals(syntax))
				emit_Usage___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Usage___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q.equals(syntax))
				emit_Usage___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     attributeName=STRING (ambiguity) (rule end)
	 */
	protected void emit_Attribute_CommaKeyword_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo Enforcement' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 *     partof=[Collection|ID] ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     partof=[Collection|ID] ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     partof=[Collection|ID] ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Obligation'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Permitted'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Collection___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo PrivateData' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     condition=STRING ',' (ambiguity) 'RefersTo Service' refertoservice+=ReferToService
	 *     condition=STRING ',' (ambiguity) ('RefersTo Service' ',')? 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     condition=STRING ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     condition=STRING ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     condition=STRING ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     partof=[Collection|ID] ',' (ambiguity) 'RefersTo Service' refertoservice+=ReferToService
	 *     partof=[Collection|ID] ',' (ambiguity) ('RefersTo Service' ',')? 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     partof=[Collection|ID] ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     partof=[Collection|ID] ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     partof=[Collection|ID] ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Collection___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo Service' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     partof=[Collection|ID] ',' ('RefersTo PrivateData' ',')? (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     partof=[Collection|ID] ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     partof=[Collection|ID] ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     partof=[Collection|ID] ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Collection___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo Enforcement' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         (ambiguity) 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         (ambiguity) 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         (ambiguity) 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         (ambiguity) 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         (ambiguity) 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         (ambiguity) 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     (
	 *         referToRecipient+=ReferToRecipient 
	 *         ',' 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         (ambiguity) 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         referToRecipient+=ReferToRecipient 
	 *         ',' 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         (ambiguity) 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         referToRecipient+=ReferToRecipient 
	 *         ',' 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         (ambiguity) 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     referToRecipientsource+=ReferToRecipientSource ',' ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     referToRecipientsource+=ReferToRecipientSource ',' ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     referToRecipientsource+=ReferToRecipientSource ',' ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 *     referToRecipienttarget+=ReferToRecipientTarget ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     referToRecipienttarget+=ReferToRecipientTarget ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     referToRecipienttarget+=ReferToRecipientTarget ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Obligation'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Permitted'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Disclosure___RefersToEnforcementKeyword_15_0_CommaKeyword_15_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo PrivateData' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Service' ',')? 
	 *         'RefersTo Enforcement' 
	 *         refertoEnforcement+=RefertoEnforcement
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Service' ',')? 
	 *         'RefersTo Enforcement' 
	 *         refertoEnforcement+=RefertoEnforcement
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     (
	 *         referToRecipient+=ReferToRecipient 
	 *         ',' 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Service' ',')? 
	 *         'RefersTo Enforcement' 
	 *         refertoEnforcement+=RefertoEnforcement
	 *     )
	 *     (
	 *         referToRecipient+=ReferToRecipient 
	 *         ',' 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         referToRecipient+=ReferToRecipient 
	 *         ',' 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         referToRecipient+=ReferToRecipient 
	 *         ',' 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     condition=STRING ',' ('RefersTo Recipient' ',')? ('RefersTo Recipient-Source' ',')? ('RefersTo Recipient-Target' ',')? (ambiguity) 'RefersTo Service' refertoservice+=ReferToService
	 *     partof=[Disclosure|ID] ',' ('RefersTo Recipient' ',')? ('RefersTo Recipient-Source' ',')? ('RefersTo Recipient-Target' ',')? (ambiguity) 'RefersTo Service' refertoservice+=ReferToService
	 *     referToRecipient+=ReferToRecipient ',' ('RefersTo Recipient-Source' ',')? ('RefersTo Recipient-Target' ',')? (ambiguity) 'RefersTo Service' refertoservice+=ReferToService
	 *     referToRecipientsource+=ReferToRecipientSource ',' ('RefersTo Recipient-Target' ',')? (ambiguity) 'RefersTo Service' refertoservice+=ReferToService
	 *     referToRecipientsource+=ReferToRecipientSource ',' ('RefersTo Recipient-Target' ',')? (ambiguity) ('RefersTo Service' ',')? 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     referToRecipientsource+=ReferToRecipientSource ',' ('RefersTo Recipient-Target' ',')? (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     referToRecipientsource+=ReferToRecipientSource ',' ('RefersTo Recipient-Target' ',')? (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     referToRecipientsource+=ReferToRecipientSource ',' ('RefersTo Recipient-Target' ',')? (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     referToRecipienttarget+=ReferToRecipientTarget ',' (ambiguity) 'RefersTo Service' refertoservice+=ReferToService
	 *     referToRecipienttarget+=ReferToRecipientTarget ',' (ambiguity) ('RefersTo Service' ',')? 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     referToRecipienttarget+=ReferToRecipientTarget ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     referToRecipienttarget+=ReferToRecipientTarget ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     referToRecipienttarget+=ReferToRecipientTarget ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Disclosure___RefersToPrivateDataKeyword_13_0_CommaKeyword_13_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo Recipient' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         'RefersTo Enforcement' 
	 *         refertoEnforcement+=RefertoEnforcement
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         'RefersTo Enforcement' 
	 *         refertoEnforcement+=RefertoEnforcement
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     condition=STRING ',' (ambiguity) 'RefersTo Recipient-Source' referToRecipientsource+=ReferToRecipientSource
	 *     condition=STRING ',' (ambiguity) ('RefersTo Recipient-Source' ',')? 'RefersTo Recipient-Target' referToRecipienttarget+=ReferToRecipientTarget
	 *     condition=STRING ',' (ambiguity) ('RefersTo Recipient-Source' ',')? ('RefersTo Recipient-Target' ',')? 'RefersTo PrivateData' refprivatedata+=RefPrivateData
	 *     condition=STRING ',' (ambiguity) ('RefersTo Recipient-Source' ',')? ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? 'RefersTo Service' refertoservice+=ReferToService
	 *     partof=[Disclosure|ID] ',' (ambiguity) 'RefersTo Recipient-Source' referToRecipientsource+=ReferToRecipientSource
	 *     partof=[Disclosure|ID] ',' (ambiguity) ('RefersTo Recipient-Source' ',')? 'RefersTo Recipient-Target' referToRecipienttarget+=ReferToRecipientTarget
	 *     partof=[Disclosure|ID] ',' (ambiguity) ('RefersTo Recipient-Source' ',')? ('RefersTo Recipient-Target' ',')? 'RefersTo PrivateData' refprivatedata+=RefPrivateData
	 *     partof=[Disclosure|ID] ',' (ambiguity) ('RefersTo Recipient-Source' ',')? ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? 'RefersTo Service' refertoservice+=ReferToService
	 */
	protected void emit_Disclosure___RefersToRecipientKeyword_10_0_CommaKeyword_10_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo Recipient-Source' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         'RefersTo Enforcement' 
	 *         refertoEnforcement+=RefertoEnforcement
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         'RefersTo Enforcement' 
	 *         refertoEnforcement+=RefertoEnforcement
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     condition=STRING ',' ('RefersTo Recipient' ',')? (ambiguity) 'RefersTo Recipient-Target' referToRecipienttarget+=ReferToRecipientTarget
	 *     condition=STRING ',' ('RefersTo Recipient' ',')? (ambiguity) ('RefersTo Recipient-Target' ',')? 'RefersTo PrivateData' refprivatedata+=RefPrivateData
	 *     condition=STRING ',' ('RefersTo Recipient' ',')? (ambiguity) ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? 'RefersTo Service' refertoservice+=ReferToService
	 *     partof=[Disclosure|ID] ',' ('RefersTo Recipient' ',')? (ambiguity) 'RefersTo Recipient-Target' referToRecipienttarget+=ReferToRecipientTarget
	 *     partof=[Disclosure|ID] ',' ('RefersTo Recipient' ',')? (ambiguity) ('RefersTo Recipient-Target' ',')? 'RefersTo PrivateData' refprivatedata+=RefPrivateData
	 *     partof=[Disclosure|ID] ',' ('RefersTo Recipient' ',')? (ambiguity) ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? 'RefersTo Service' refertoservice+=ReferToService
	 *     referToRecipient+=ReferToRecipient ',' (ambiguity) 'RefersTo Recipient-Target' referToRecipienttarget+=ReferToRecipientTarget
	 *     referToRecipient+=ReferToRecipient ',' (ambiguity) ('RefersTo Recipient-Target' ',')? 'RefersTo PrivateData' refprivatedata+=RefPrivateData
	 *     referToRecipient+=ReferToRecipient ',' (ambiguity) ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? 'RefersTo Service' refertoservice+=ReferToService
	 *     referToRecipient+=ReferToRecipient ',' (ambiguity) ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     referToRecipient+=ReferToRecipient ',' (ambiguity) ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     referToRecipient+=ReferToRecipient ',' (ambiguity) ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     referToRecipient+=ReferToRecipient ',' (ambiguity) ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Disclosure___RefersToRecipientSourceKeyword_11_0_CommaKeyword_11_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo Recipient-Target' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         'RefersTo Enforcement' 
	 *         refertoEnforcement+=RefertoEnforcement
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         'RefersTo Enforcement' 
	 *         refertoEnforcement+=RefertoEnforcement
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo PrivateData' ',')? 
	 *         ('RefersTo Service' ',')? 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     condition=STRING ',' ('RefersTo Recipient' ',')? ('RefersTo Recipient-Source' ',')? (ambiguity) 'RefersTo PrivateData' refprivatedata+=RefPrivateData
	 *     condition=STRING ',' ('RefersTo Recipient' ',')? ('RefersTo Recipient-Source' ',')? (ambiguity) ('RefersTo PrivateData' ',')? 'RefersTo Service' refertoservice+=ReferToService
	 *     partof=[Disclosure|ID] ',' ('RefersTo Recipient' ',')? ('RefersTo Recipient-Source' ',')? (ambiguity) 'RefersTo PrivateData' refprivatedata+=RefPrivateData
	 *     partof=[Disclosure|ID] ',' ('RefersTo Recipient' ',')? ('RefersTo Recipient-Source' ',')? (ambiguity) ('RefersTo PrivateData' ',')? 'RefersTo Service' refertoservice+=ReferToService
	 *     referToRecipient+=ReferToRecipient ',' ('RefersTo Recipient-Source' ',')? (ambiguity) 'RefersTo PrivateData' refprivatedata+=RefPrivateData
	 *     referToRecipient+=ReferToRecipient ',' ('RefersTo Recipient-Source' ',')? (ambiguity) ('RefersTo PrivateData' ',')? 'RefersTo Service' refertoservice+=ReferToService
	 *     referToRecipient+=ReferToRecipient ',' ('RefersTo Recipient-Source' ',')? (ambiguity) ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     referToRecipient+=ReferToRecipient ',' ('RefersTo Recipient-Source' ',')? (ambiguity) ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     referToRecipient+=ReferToRecipient ',' ('RefersTo Recipient-Source' ',')? (ambiguity) ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     referToRecipient+=ReferToRecipient ',' ('RefersTo Recipient-Source' ',')? (ambiguity) ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     referToRecipientsource+=ReferToRecipientSource ',' (ambiguity) 'RefersTo PrivateData' refprivatedata+=RefPrivateData
	 *     referToRecipientsource+=ReferToRecipientSource ',' (ambiguity) ('RefersTo PrivateData' ',')? 'RefersTo Service' refertoservice+=ReferToService
	 *     referToRecipientsource+=ReferToRecipientSource ',' (ambiguity) ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     referToRecipientsource+=ReferToRecipientSource ',' (ambiguity) ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     referToRecipientsource+=ReferToRecipientSource ',' (ambiguity) ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     referToRecipientsource+=ReferToRecipientSource ',' (ambiguity) ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Disclosure___RefersToRecipientTargetKeyword_12_0_CommaKeyword_12_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo Service' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         (ambiguity) 
	 *         'RefersTo Enforcement' 
	 *         refertoEnforcement+=RefertoEnforcement
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         condition=STRING 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         (ambiguity) 
	 *         'RefersTo Enforcement' 
	 *         refertoEnforcement+=RefertoEnforcement
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         partof=[Disclosure|ID] 
	 *         ',' 
	 *         ('RefersTo Recipient' ',')? 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     (
	 *         referToRecipient+=ReferToRecipient 
	 *         ',' 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         (ambiguity) 
	 *         'RefersTo Enforcement' 
	 *         refertoEnforcement+=RefertoEnforcement
	 *     )
	 *     (
	 *         referToRecipient+=ReferToRecipient 
	 *         ',' 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Forbidden'
	 *     )
	 *     (
	 *         referToRecipient+=ReferToRecipient 
	 *         ',' 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Obligation'
	 *     )
	 *     (
	 *         referToRecipient+=ReferToRecipient 
	 *         ',' 
	 *         ('RefersTo Recipient-Source' ',')? 
	 *         ('RefersTo Recipient-Target' ',')? 
	 *         ('RefersTo PrivateData' ',')? 
	 *         (ambiguity) 
	 *         ('RefersTo Enforcement' ',')? 
	 *         'Modality' 
	 *         modalitykind='Permitted'
	 *     )
	 *     referToRecipientsource+=ReferToRecipientSource ',' ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     referToRecipientsource+=ReferToRecipientSource ',' ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     referToRecipientsource+=ReferToRecipientSource ',' ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     referToRecipientsource+=ReferToRecipientSource ',' ('RefersTo Recipient-Target' ',')? ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     referToRecipienttarget+=ReferToRecipientTarget ',' ('RefersTo PrivateData' ',')? (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     referToRecipienttarget+=ReferToRecipientTarget ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     referToRecipienttarget+=ReferToRecipientTarget ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     referToRecipienttarget+=ReferToRecipientTarget ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Disclosure___RefersToServiceKeyword_14_0_CommaKeyword_14_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo Enforcement' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 *     partof=[Informative|ID] ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     partof=[Informative|ID] ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     partof=[Informative|ID] ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Obligation'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Permitted'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Informative___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo PrivateData' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     condition=STRING ',' (ambiguity) 'RefersTo Service' refertoservice+=ReferToService
	 *     condition=STRING ',' (ambiguity) ('RefersTo Service' ',')? 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     condition=STRING ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     condition=STRING ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     condition=STRING ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     partof=[Informative|ID] ',' (ambiguity) 'RefersTo Service' refertoservice+=ReferToService
	 *     partof=[Informative|ID] ',' (ambiguity) ('RefersTo Service' ',')? 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     partof=[Informative|ID] ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     partof=[Informative|ID] ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     partof=[Informative|ID] ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Informative___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo Service' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     partof=[Informative|ID] ',' ('RefersTo PrivateData' ',')? (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     partof=[Informative|ID] ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     partof=[Informative|ID] ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     partof=[Informative|ID] ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Informative___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '-'?
	 *
	 * This ambiguous syntax occurs at:
	 *     partof=[Recipient|ID] (ambiguity) (rule end)
	 */
	protected void emit_Partof_HyphenMinusKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('Recipient_Part' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     description=STRING ',' (ambiguity) 'Scope' RecipientScopeKind='External'
	 *     description=STRING ',' (ambiguity) 'Scope' RecipientScopeKind='Internal'
	 *     description=STRING ',' (ambiguity) 'Scope' RecipientScopeKind='Internal/External'
	 */
	protected void emit_Recipient___Recipient_PartKeyword_9_0_CommaKeyword_9_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '-'?
	 *
	 * This ambiguous syntax occurs at:
	 *     refpr=[PrivateData|ID] (ambiguity) (rule end)
	 */
	protected void emit_RefPrivateData_HyphenMinusKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '-'?
	 *
	 * This ambiguous syntax occurs at:
	 *     refertore=[Recipient|ID] (ambiguity) (rule end)
	 */
	protected void emit_ReferToRecipientSource_HyphenMinusKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '-'?
	 *
	 * This ambiguous syntax occurs at:
	 *     refertore=[Recipient|ID] (ambiguity) (rule end)
	 */
	protected void emit_ReferToRecipientTarget_HyphenMinusKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '-'?
	 *
	 * This ambiguous syntax occurs at:
	 *     refertore=[Recipient|ID] (ambiguity) (rule end)
	 */
	protected void emit_ReferToRecipient_HyphenMinusKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '-'?
	 *
	 * This ambiguous syntax occurs at:
	 *     refertose=[Service|ID] (ambiguity) (rule end)
	 */
	protected void emit_ReferToService_HyphenMinusKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '-'?
	 *
	 * This ambiguous syntax occurs at:
	 *     refst=[Enforcement|ID] (ambiguity) (rule end)
	 */
	protected void emit_RefertoEnforcement_HyphenMinusKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo Enforcement' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     period=STRING ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     period=STRING ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     period=STRING ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Obligation'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Permitted'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Retention___RefersToEnforcementKeyword_15_0_CommaKeyword_15_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo PrivateData' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     period=STRING ',' (ambiguity) 'RefersTo Service' refertoservice+=ReferToService
	 *     period=STRING ',' (ambiguity) ('RefersTo Service' ',')? 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     period=STRING ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     period=STRING ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     period=STRING ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Retention___RefersToPrivateDataKeyword_13_0_CommaKeyword_13_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo Service' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     period=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     period=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     period=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     period=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Retention___RefersToServiceKeyword_14_0_CommaKeyword_14_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '-'?
	 *
	 * This ambiguous syntax occurs at:
	 *     refertoservice=[Service|ID] (ambiguity) (rule end)
	 */
	protected void emit_ServicePartof_HyphenMinusKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Service_Part'?
	 *
	 * This ambiguous syntax occurs at:
	 *     description=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) '};' (rule end)
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) '};' (rule end)
	 *     servicename=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) '};' (rule end)
	 */
	protected void emit_Service_Service_PartKeyword_8_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo PrivateData' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     description=STRING ',' (ambiguity) 'Service_Part' servicepartof+=ServicePartof
	 *     description=STRING ',' (ambiguity) 'Service_Part'? '};' (rule end)
	 *     servicename=STRING ',' (ambiguity) 'Service_Part' servicepartof+=ServicePartof
	 *     servicename=STRING ',' (ambiguity) 'Service_Part'? '};' (rule end)
	 */
	protected void emit_Service___RefersToPrivateDataKeyword_7_0_CommaKeyword_7_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo Enforcement' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 *     partof=[Usage|ID] ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     partof=[Usage|ID] ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     partof=[Usage|ID] ',' ('RefersTo PrivateData' ',')? ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Obligation'
	 *     refertoservice+=ReferToService ',' (ambiguity) 'Modality' modalitykind='Permitted'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Forbidden'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Obligation'
	 *     refprivatedata+=RefPrivateData ',' ('RefersTo Service' ',')? (ambiguity) 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Usage___RefersToEnforcementKeyword_12_0_CommaKeyword_12_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo PrivateData' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     condition=STRING ',' (ambiguity) 'RefersTo Service' refertoservice+=ReferToService
	 *     condition=STRING ',' (ambiguity) ('RefersTo Service' ',')? 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     condition=STRING ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     condition=STRING ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     condition=STRING ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     partof=[Usage|ID] ',' (ambiguity) 'RefersTo Service' refertoservice+=ReferToService
	 *     partof=[Usage|ID] ',' (ambiguity) ('RefersTo Service' ',')? 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     partof=[Usage|ID] ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     partof=[Usage|ID] ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     partof=[Usage|ID] ',' (ambiguity) ('RefersTo Service' ',')? ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Usage___RefersToPrivateDataKeyword_10_0_CommaKeyword_10_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('RefersTo Service' ',')?
	 *
	 * This ambiguous syntax occurs at:
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     condition=STRING ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     partof=[Usage|ID] ',' ('RefersTo PrivateData' ',')? (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     partof=[Usage|ID] ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     partof=[Usage|ID] ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     partof=[Usage|ID] ',' ('RefersTo PrivateData' ',')? (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) 'RefersTo Enforcement' refertoEnforcement+=RefertoEnforcement
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Forbidden'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Obligation'
	 *     refprivatedata+=RefPrivateData ',' (ambiguity) ('RefersTo Enforcement' ',')? 'Modality' modalitykind='Permitted'
	 */
	protected void emit_Usage___RefersToServiceKeyword_11_0_CommaKeyword_11_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
