/*
 * generated by Xtext
 */
package rslingo.rslil4privacy.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import rslingo.rslil4privacy.services.RSLIL4PrivacyGrammarAccess;

public class RSLIL4PrivacyParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RSLIL4PrivacyGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected rslingo.rslil4privacy.parser.antlr.internal.InternalRSLIL4PrivacyParser createParser(XtextTokenStream stream) {
		return new rslingo.rslil4privacy.parser.antlr.internal.InternalRSLIL4PrivacyParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Policy";
	}
	
	public RSLIL4PrivacyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RSLIL4PrivacyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
