/*
 * generated by Xtext
 */
package rslingo.rslil4privacy.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RSLIL4PrivacyAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("rslingo/rslil4privacy/parser/antlr/internal/InternalRSLIL4Privacy.tokens");
	}
}
