/**
 * generated by Xtext
 */
package rslingo.rslil4privacy.validation;

import rslingo.rslil4privacy.validation.AbstractRSLIL4PrivacyValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RSLIL4PrivacyValidator extends AbstractRSLIL4PrivacyValidator {
}
