/*
 * generated by Xtext
 */
package rslingo.rslil4privacy.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import rslingo.rslil4privacy.services.RSLIL4PrivacyGrammarAccess;

public class RSLIL4PrivacyParser extends AbstractContentAssistParser {
	
	@Inject
	private RSLIL4PrivacyGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected rslingo.rslil4privacy.ui.contentassist.antlr.internal.InternalRSLIL4PrivacyParser createParser() {
		rslingo.rslil4privacy.ui.contentassist.antlr.internal.InternalRSLIL4PrivacyParser result = new rslingo.rslil4privacy.ui.contentassist.antlr.internal.InternalRSLIL4PrivacyParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEnforcementAccess().getTypeAlternatives_10_0(), "rule__Enforcement__TypeAlternatives_10_0");
					put(grammarAccess.getRecipientAccess().getScopeAlternatives_11_0(), "rule__Recipient__ScopeAlternatives_11_0");
					put(grammarAccess.getRecipientAccess().getTypeAlternatives_14_0(), "rule__Recipient__TypeAlternatives_14_0");
					put(grammarAccess.getPrivateDataAccess().getTypeAlternatives_7_0(), "rule__PrivateData__TypeAlternatives_7_0");
					put(grammarAccess.getCollectionAccess().getModalityAlternatives_14_0(), "rule__Collection__ModalityAlternatives_14_0");
					put(grammarAccess.getDisclosureAccess().getModalityAlternatives_17_0(), "rule__Disclosure__ModalityAlternatives_17_0");
					put(grammarAccess.getRetentionAccess().getModalityAlternatives_17_0(), "rule__Retention__ModalityAlternatives_17_0");
					put(grammarAccess.getUsageAccess().getModalityAlternatives_14_0(), "rule__Usage__ModalityAlternatives_14_0");
					put(grammarAccess.getInformativeAccess().getModalityAlternatives_14_0(), "rule__Informative__ModalityAlternatives_14_0");
					put(grammarAccess.getPolicyAccess().getGroup(), "rule__Policy__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getEnforcementAccess().getGroup(), "rule__Enforcement__Group__0");
					put(grammarAccess.getServiceAccess().getGroup(), "rule__Service__Group__0");
					put(grammarAccess.getServiceAccess().getGroup_6(), "rule__Service__Group_6__0");
					put(grammarAccess.getServiceAccess().getGroup_7(), "rule__Service__Group_7__0");
					put(grammarAccess.getServiceAccess().getGroup_8(), "rule__Service__Group_8__0");
					put(grammarAccess.getRecipientAccess().getGroup(), "rule__Recipient__Group__0");
					put(grammarAccess.getRecipientAccess().getGroup_9(), "rule__Recipient__Group_9__0");
					put(grammarAccess.getPrivateDataAccess().getGroup(), "rule__PrivateData__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getCollectionAccess().getGroup(), "rule__Collection__Group__0");
					put(grammarAccess.getCollectionAccess().getGroup_9(), "rule__Collection__Group_9__0");
					put(grammarAccess.getCollectionAccess().getGroup_10(), "rule__Collection__Group_10__0");
					put(grammarAccess.getCollectionAccess().getGroup_11(), "rule__Collection__Group_11__0");
					put(grammarAccess.getCollectionAccess().getGroup_12(), "rule__Collection__Group_12__0");
					put(grammarAccess.getDisclosureAccess().getGroup(), "rule__Disclosure__Group__0");
					put(grammarAccess.getDisclosureAccess().getGroup_9(), "rule__Disclosure__Group_9__0");
					put(grammarAccess.getDisclosureAccess().getGroup_10(), "rule__Disclosure__Group_10__0");
					put(grammarAccess.getDisclosureAccess().getGroup_11(), "rule__Disclosure__Group_11__0");
					put(grammarAccess.getDisclosureAccess().getGroup_12(), "rule__Disclosure__Group_12__0");
					put(grammarAccess.getDisclosureAccess().getGroup_13(), "rule__Disclosure__Group_13__0");
					put(grammarAccess.getDisclosureAccess().getGroup_14(), "rule__Disclosure__Group_14__0");
					put(grammarAccess.getDisclosureAccess().getGroup_15(), "rule__Disclosure__Group_15__0");
					put(grammarAccess.getRetentionAccess().getGroup(), "rule__Retention__Group__0");
					put(grammarAccess.getRetentionAccess().getGroup_9(), "rule__Retention__Group_9__0");
					put(grammarAccess.getRetentionAccess().getGroup_13(), "rule__Retention__Group_13__0");
					put(grammarAccess.getRetentionAccess().getGroup_14(), "rule__Retention__Group_14__0");
					put(grammarAccess.getRetentionAccess().getGroup_15(), "rule__Retention__Group_15__0");
					put(grammarAccess.getUsageAccess().getGroup(), "rule__Usage__Group__0");
					put(grammarAccess.getUsageAccess().getGroup_9(), "rule__Usage__Group_9__0");
					put(grammarAccess.getUsageAccess().getGroup_10(), "rule__Usage__Group_10__0");
					put(grammarAccess.getUsageAccess().getGroup_11(), "rule__Usage__Group_11__0");
					put(grammarAccess.getUsageAccess().getGroup_12(), "rule__Usage__Group_12__0");
					put(grammarAccess.getInformativeAccess().getGroup(), "rule__Informative__Group__0");
					put(grammarAccess.getInformativeAccess().getGroup_9(), "rule__Informative__Group_9__0");
					put(grammarAccess.getInformativeAccess().getGroup_10(), "rule__Informative__Group_10__0");
					put(grammarAccess.getInformativeAccess().getGroup_11(), "rule__Informative__Group_11__0");
					put(grammarAccess.getInformativeAccess().getGroup_12(), "rule__Informative__Group_12__0");
					put(grammarAccess.getRecipientPartAccess().getGroup(), "rule__RecipientPart__Group__0");
					put(grammarAccess.getRefRecipientAccess().getGroup(), "rule__RefRecipient__Group__0");
					put(grammarAccess.getRefRecipientSourceAccess().getGroup(), "rule__RefRecipientSource__Group__0");
					put(grammarAccess.getRefRecipientTargetAccess().getGroup(), "rule__RefRecipientTarget__Group__0");
					put(grammarAccess.getRefServiceAccess().getGroup(), "rule__RefService__Group__0");
					put(grammarAccess.getServicePartAccess().getGroup(), "rule__ServicePart__Group__0");
					put(grammarAccess.getRefPrivateDataAccess().getGroup(), "rule__RefPrivateData__Group__0");
					put(grammarAccess.getRefEnforcementAccess().getGroup(), "rule__RefEnforcement__Group__0");
					put(grammarAccess.getPolicyAccess().getNameAssignment_1(), "rule__Policy__NameAssignment_1");
					put(grammarAccess.getPolicyAccess().getImportelementsAssignment_3(), "rule__Policy__ImportelementsAssignment_3");
					put(grammarAccess.getPolicyAccess().getCollectionAssignment_4(), "rule__Policy__CollectionAssignment_4");
					put(grammarAccess.getPolicyAccess().getDisclosureAssignment_5(), "rule__Policy__DisclosureAssignment_5");
					put(grammarAccess.getPolicyAccess().getRetentionAssignment_6(), "rule__Policy__RetentionAssignment_6");
					put(grammarAccess.getPolicyAccess().getUsageAssignment_7(), "rule__Policy__UsageAssignment_7");
					put(grammarAccess.getPolicyAccess().getInformativeAssignment_8(), "rule__Policy__InformativeAssignment_8");
					put(grammarAccess.getPolicyAccess().getPrivateDataAssignment_9(), "rule__Policy__PrivateDataAssignment_9");
					put(grammarAccess.getPolicyAccess().getRecipientAssignment_10(), "rule__Policy__RecipientAssignment_10");
					put(grammarAccess.getPolicyAccess().getServiceAssignment_11(), "rule__Policy__ServiceAssignment_11");
					put(grammarAccess.getPolicyAccess().getEnforcementAssignment_12(), "rule__Policy__EnforcementAssignment_12");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getEnforcementAccess().getNameAssignment_1(), "rule__Enforcement__NameAssignment_1");
					put(grammarAccess.getEnforcementAccess().getEnforcementNameAssignment_4(), "rule__Enforcement__EnforcementNameAssignment_4");
					put(grammarAccess.getEnforcementAccess().getDescriptionAssignment_7(), "rule__Enforcement__DescriptionAssignment_7");
					put(grammarAccess.getEnforcementAccess().getTypeAssignment_10(), "rule__Enforcement__TypeAssignment_10");
					put(grammarAccess.getServiceAccess().getNameAssignment_1(), "rule__Service__NameAssignment_1");
					put(grammarAccess.getServiceAccess().getServiceNameAssignment_4(), "rule__Service__ServiceNameAssignment_4");
					put(grammarAccess.getServiceAccess().getDescriptionAssignment_6_1(), "rule__Service__DescriptionAssignment_6_1");
					put(grammarAccess.getServiceAccess().getRefPrivateDataAssignment_7_1(), "rule__Service__RefPrivateDataAssignment_7_1");
					put(grammarAccess.getServiceAccess().getServicePartAssignment_8_1(), "rule__Service__ServicePartAssignment_8_1");
					put(grammarAccess.getRecipientAccess().getNameAssignment_1(), "rule__Recipient__NameAssignment_1");
					put(grammarAccess.getRecipientAccess().getRecipientNameAssignment_4(), "rule__Recipient__RecipientNameAssignment_4");
					put(grammarAccess.getRecipientAccess().getDescriptionAssignment_7(), "rule__Recipient__DescriptionAssignment_7");
					put(grammarAccess.getRecipientAccess().getRecipientPartAssignment_9_1(), "rule__Recipient__RecipientPartAssignment_9_1");
					put(grammarAccess.getRecipientAccess().getScopeAssignment_11(), "rule__Recipient__ScopeAssignment_11");
					put(grammarAccess.getRecipientAccess().getTypeAssignment_14(), "rule__Recipient__TypeAssignment_14");
					put(grammarAccess.getPrivateDataAccess().getNameAssignment_1(), "rule__PrivateData__NameAssignment_1");
					put(grammarAccess.getPrivateDataAccess().getDescriptionAssignment_4(), "rule__PrivateData__DescriptionAssignment_4");
					put(grammarAccess.getPrivateDataAccess().getTypeAssignment_7(), "rule__PrivateData__TypeAssignment_7");
					put(grammarAccess.getPrivateDataAccess().getAttributeAssignment_9(), "rule__PrivateData__AttributeAssignment_9");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
					put(grammarAccess.getAttributeAccess().getDescriptionAssignment_3(), "rule__Attribute__DescriptionAssignment_3");
					put(grammarAccess.getCollectionAccess().getNameAssignment_1(), "rule__Collection__NameAssignment_1");
					put(grammarAccess.getCollectionAccess().getDescriptionAssignment_4(), "rule__Collection__DescriptionAssignment_4");
					put(grammarAccess.getCollectionAccess().getConditionAssignment_7(), "rule__Collection__ConditionAssignment_7");
					put(grammarAccess.getCollectionAccess().getPartCollectionAssignment_9_1(), "rule__Collection__PartCollectionAssignment_9_1");
					put(grammarAccess.getCollectionAccess().getRefPrivateDataAssignment_10_1(), "rule__Collection__RefPrivateDataAssignment_10_1");
					put(grammarAccess.getCollectionAccess().getRefServiceAssignment_11_1(), "rule__Collection__RefServiceAssignment_11_1");
					put(grammarAccess.getCollectionAccess().getRefEnforcementAssignment_12_1(), "rule__Collection__RefEnforcementAssignment_12_1");
					put(grammarAccess.getCollectionAccess().getModalityAssignment_14(), "rule__Collection__ModalityAssignment_14");
					put(grammarAccess.getDisclosureAccess().getNameAssignment_1(), "rule__Disclosure__NameAssignment_1");
					put(grammarAccess.getDisclosureAccess().getDescriptionAssignment_4(), "rule__Disclosure__DescriptionAssignment_4");
					put(grammarAccess.getDisclosureAccess().getConditionAssignment_7(), "rule__Disclosure__ConditionAssignment_7");
					put(grammarAccess.getDisclosureAccess().getPartDisclosureAssignment_9_1(), "rule__Disclosure__PartDisclosureAssignment_9_1");
					put(grammarAccess.getDisclosureAccess().getRefRecipientAssignment_10_1(), "rule__Disclosure__RefRecipientAssignment_10_1");
					put(grammarAccess.getDisclosureAccess().getRefRecipientSourceAssignment_11_1(), "rule__Disclosure__RefRecipientSourceAssignment_11_1");
					put(grammarAccess.getDisclosureAccess().getRefRecipientTargetAssignment_12_1(), "rule__Disclosure__RefRecipientTargetAssignment_12_1");
					put(grammarAccess.getDisclosureAccess().getRefPrivateDataAssignment_13_1(), "rule__Disclosure__RefPrivateDataAssignment_13_1");
					put(grammarAccess.getDisclosureAccess().getRefServiceAssignment_14_1(), "rule__Disclosure__RefServiceAssignment_14_1");
					put(grammarAccess.getDisclosureAccess().getRefEnforcementAssignment_15_1(), "rule__Disclosure__RefEnforcementAssignment_15_1");
					put(grammarAccess.getDisclosureAccess().getModalityAssignment_17(), "rule__Disclosure__ModalityAssignment_17");
					put(grammarAccess.getRetentionAccess().getNameAssignment_1(), "rule__Retention__NameAssignment_1");
					put(grammarAccess.getRetentionAccess().getDescriptionAssignment_4(), "rule__Retention__DescriptionAssignment_4");
					put(grammarAccess.getRetentionAccess().getConditionAssignment_7(), "rule__Retention__ConditionAssignment_7");
					put(grammarAccess.getRetentionAccess().getPartRetentionAssignment_9_1(), "rule__Retention__PartRetentionAssignment_9_1");
					put(grammarAccess.getRetentionAccess().getPeriodAssignment_11(), "rule__Retention__PeriodAssignment_11");
					put(grammarAccess.getRetentionAccess().getRefPrivateDataAssignment_13_1(), "rule__Retention__RefPrivateDataAssignment_13_1");
					put(grammarAccess.getRetentionAccess().getRefServiceAssignment_14_1(), "rule__Retention__RefServiceAssignment_14_1");
					put(grammarAccess.getRetentionAccess().getRefEnforcementAssignment_15_1(), "rule__Retention__RefEnforcementAssignment_15_1");
					put(grammarAccess.getRetentionAccess().getModalityAssignment_17(), "rule__Retention__ModalityAssignment_17");
					put(grammarAccess.getUsageAccess().getNameAssignment_1(), "rule__Usage__NameAssignment_1");
					put(grammarAccess.getUsageAccess().getDescriptionAssignment_4(), "rule__Usage__DescriptionAssignment_4");
					put(grammarAccess.getUsageAccess().getConditionAssignment_7(), "rule__Usage__ConditionAssignment_7");
					put(grammarAccess.getUsageAccess().getPartUsageAssignment_9_1(), "rule__Usage__PartUsageAssignment_9_1");
					put(grammarAccess.getUsageAccess().getRefPrivateDataAssignment_10_1(), "rule__Usage__RefPrivateDataAssignment_10_1");
					put(grammarAccess.getUsageAccess().getRefServiceAssignment_11_1(), "rule__Usage__RefServiceAssignment_11_1");
					put(grammarAccess.getUsageAccess().getRefEnforcementAssignment_12_1(), "rule__Usage__RefEnforcementAssignment_12_1");
					put(grammarAccess.getUsageAccess().getModalityAssignment_14(), "rule__Usage__ModalityAssignment_14");
					put(grammarAccess.getInformativeAccess().getNameAssignment_1(), "rule__Informative__NameAssignment_1");
					put(grammarAccess.getInformativeAccess().getDescriptionAssignment_4(), "rule__Informative__DescriptionAssignment_4");
					put(grammarAccess.getInformativeAccess().getConditionAssignment_7(), "rule__Informative__ConditionAssignment_7");
					put(grammarAccess.getInformativeAccess().getPartInformativeAssignment_9_1(), "rule__Informative__PartInformativeAssignment_9_1");
					put(grammarAccess.getInformativeAccess().getRefPrivateDataAssignment_10_1(), "rule__Informative__RefPrivateDataAssignment_10_1");
					put(grammarAccess.getInformativeAccess().getRefServiceAssignment_11_1(), "rule__Informative__RefServiceAssignment_11_1");
					put(grammarAccess.getInformativeAccess().getRefEnforcementAssignment_12_1(), "rule__Informative__RefEnforcementAssignment_12_1");
					put(grammarAccess.getInformativeAccess().getModalityAssignment_14(), "rule__Informative__ModalityAssignment_14");
					put(grammarAccess.getRecipientPartAccess().getRecipientPartAssignment_0(), "rule__RecipientPart__RecipientPartAssignment_0");
					put(grammarAccess.getRefRecipientAccess().getRefRecipientAssignment_0(), "rule__RefRecipient__RefRecipientAssignment_0");
					put(grammarAccess.getRefRecipientSourceAccess().getRefRecipientSourceAssignment_0(), "rule__RefRecipientSource__RefRecipientSourceAssignment_0");
					put(grammarAccess.getRefRecipientTargetAccess().getRefRecipientTargetAssignment_0(), "rule__RefRecipientTarget__RefRecipientTargetAssignment_0");
					put(grammarAccess.getRefServiceAccess().getRefServiceAssignment_0(), "rule__RefService__RefServiceAssignment_0");
					put(grammarAccess.getServicePartAccess().getServicePartAssignment_0(), "rule__ServicePart__ServicePartAssignment_0");
					put(grammarAccess.getRefPrivateDataAccess().getRefPrivateDataAssignment_0(), "rule__RefPrivateData__RefPrivateDataAssignment_0");
					put(grammarAccess.getRefEnforcementAccess().getRefEnforcementAssignment_0(), "rule__RefEnforcement__RefEnforcementAssignment_0");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			rslingo.rslil4privacy.ui.contentassist.antlr.internal.InternalRSLIL4PrivacyParser typedParser = (rslingo.rslil4privacy.ui.contentassist.antlr.internal.InternalRSLIL4PrivacyParser) parser;
			typedParser.entryRulePolicy();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RSLIL4PrivacyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RSLIL4PrivacyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
