/*
 * generated by Xtext
 */
package rslingo.rslil4privacy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RSLIL4PrivacyRuntimeModule extends rslingo.rslil4privacy.AbstractRSLIL4PrivacyRuntimeModule {

}
